### ISSUE TITLE
"Push in julia.ipynb" dosen´t work

### ISSUE THREAD

**Issue by ferkawalon** [emmaccode/Emmys-NoteBooks#3]
@emmettgb  "Error in Push in julia.ipynb2 Emmetts-DS-NoteBooks 
------------------
push!(collection::Vector{Int64}, range::UnitRange)
This method can be used to unpack a range generator and return its elements pushed into the collection.
after your Out[40]  and before In[42] ( there is a In[41]  afther In[42])  
there is an typo error just  a "," missing 
`julia>push!([2, 3] 1:2) `             " of course no run without ",".
but  neither
 `=>push!([2, 3] , 1:2)**`
( I am running JupytherNB in julia 1.8.5 ) 
![Screenshot from 2023-04-28 10-16-18](https://user-images.githubusercontent.com/7437502/235093825-b8bdf707-72a7-4509-92b6-f7867100c0d6.png)

**Comment by ferkawalon** [comment]
Morning. I saw you comment the same error in your article *"Everything-You-Need-to-Know-about-Push!-in-julia-"* (29 Dec 2021)
just below subtitle *"More with push!()".* The date of this source GIT is 26 Dec 2021.
I don´t understand what you want to do.....

**Comment by emmaccode** [comment]
sorry just getting to this, this is only in the doc-string, I guess we could fix it or leave it -- I will correct it when I end up using a notebook again!

**Comment by emmaccode** [comment]
```julia

"""## push!(collection::Vector{Int64}, range::UnitRange)
This method can be used to unpack a range generator and return its elements pushed into the collection. \
```
julia> push!([2, 3] 1:2)

4-element Vector{Int64}
2
3
1
2
```

"""
import Base: push!
function push!(collection::Vector{Int64}, range::UnitRange{Int64})
    [push!(collection, i) for i in range]
end
```
Does the code above not fix this`MethodError`?

**Comment by ferkawalon** [comment]
" _Does the code above not fix thisMethodError ?_ " ....yes of course, I wanted to let you know.
Thanks for all yours articles .... I will continue to read them with interest.
Sincerely.

**Comment by emmaccode** [comment]
gotcha, thanks! closing :) <3

**Comment by ferkawalon** [comment]
Hi, grateful.
Allow me tell you that
I would like to know your vision about two themes. Because I have some
questions without good answers.
The themes are about environments and the second about some "types" and "
== ",     " ===" and "isequal" functions.
I'm not in a hurry, and also I guess you're totally busy ... but from these
themes you could extract some future articles.
I have found very few Julia authors that want to understand the language
deeply.
Without commitment ...
Sincerely.
Fernando,
